<?php
declare(strict_types=1);

/** @var \Yireo\ExampleDealersStorefront\ViewModel\Dealers $dealersViewModel */
$dealersViewModel = $block->getDealersViewModel();
$dealers = $dealersViewModel->getDealers();
?>
<h1>Example dealers</h1>
<?php if ($dealers) : ?>
<table>
    <thead>
    <th>ID</th>
    <th>Name</th>
    </thead>
    <tbody>
    <?php foreach($dealers as $dealer): ?>
    <tr>
        <td><?= $dealer->getId() ?></td>
        <td><?= $dealer->getName() ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
No dealers found
<?php endif; ?>
